### PR TITLE
set note for to-be-approved posts at writing areas

### PR DESCRIPTION
**Pull request by Haikuch**
New users don't get a proper information that their posts need to be approved first. It only flashes by for some seconds while the page is redirecting after the post.

The issue has been reported here: https://forum.openstreetmap.org/viewtopic.php?pid=615495#p615495

The update will put a explicit note for this users at the write areas.

### CODE REVIEW

**Comment by Haikuch** [comment]
> Not sure if you meant to close this, but this doesn't look like something that is OSM specific, so I imagine it should be addressed upstream, not here.

this updates the "Moderator Post Approval Modification" not the fluxbb master, so there is no upstream for this. Also the Moderator Post Approval Modification has been fixed for the OSM 1.6 version. 

See also that this has been reported in the OSM forum: https://forum.openstreetmap.org/viewtopic.php?pid=615495#p615495

**Comment by tomhughes** [comment]
So are you saying this problem is a result of rebasing to the newer fluxbb?

**Comment by tomhughes** [comment]
Also, if that mod really doesn't have an upstream then that makes me very nervous, because it means we're going to have to maintain it if we want to be able to update to new versions of fluxbb.

Well I mean it makes me pretty nervous anyway given how horribly invasive it is, but there's not much we can do about that.

**Comment by Haikuch** [comment]
no its not, its actually a problem of the Modification, but there is also no github repo for the Modification. I already sent to them the modifications that resulted from the rebasing so they can fix the mod for 1.6 and I will also send them this fix.

**Comment by tomhughes** [comment]
OK. That's good at least.

**Comment by Haikuch** [comment]
anyway, its a problem of the software that its not really hookable and needs modification to extend it.

So, at the current state of the forum, it wont be easily possible to update it anyway. Like it wasn't updated to current 1.6 and running on 1.58 for longer time

**Comment by tomhughes** [comment]
Merged as 9c763d0b08dcac31866ff9c41c22c15b1a6483fb.

**Pull request closed without merging**
