### PR TITLE
Update to Fluxbb 1.5.10

### PR DESCRIPTION
**Pull request by Haikuch**
As a basis for fixing issues etc. I updated the repo to the current 1.5.10 version of Fluxbb. There aren't any changes for the DB structure needed for 1.5.10. 
All modifications that has been done for the OSM Forum have been manually merged. That includes
- Moderator Post Approval modification
- open links in new window modification
- stop trying to send emails to empty addresses
- special osm.org login function

(unfortunately I did all the merging in a single commit)

### CODE REVIEW

**Comment by tomhughes** [comment]
So this definitely needs to be done as a rebase to preserve the commit history.

But the main reason I didn't do this myself is that I had no way to validate the result. In particular the moderator post approval modification is largae and highly invasive and is not listed upstream (https://fluxbb.org/resources/mods/moderator-post-approval/releases/1.0/) as compatible with any newer versions.

**Comment by Haikuch** [comment]
> So this definitely needs to be done as a rebase to preserve the commit history.

what do you mean by that? Because the modifications are done in a single commit?

> moderator post approval

Yes because there is no official newer version, I checked the whole code what its changing in the 1.8. Then I added the modifications to the newer version, checking every change by hand. Most of the time its just extending the where clause for the approved status. Its invasive but not very complex.

**Comment by tomhughes** [comment]
I mean that the correct way to do it is to checkout the branch and do `git rebase fluxbb-1.5.10` which will than replay each of the commits on the branch against the new release, stopping for you to fix any merge conflicts.

That way you will wind up with the same set of commits but built on top of the new version.

**Comment by Haikuch** [comment]
(_sorry, I was not really online in the last days_)

But true, the pull request here is dirty. So I did a rebase like you said and pushed it to my fork: https://github.com/Haikuch/openstreetmap-forum/commits/openstreetmap-1.5.10

Most of the merge was possible without conflicts, problems could be solved manually while checking the code. I did several diffs and tested it in the browser, works fine.

But actually, I dont know if I should make a pull request to the openstreetmap branch at your fork now? I guess that would cause again the same conflicts, maybe a new branch would be needed.

**Comment by Haikuch** [comment]
I just made a new pull request to master branch: https://github.com/openstreetmap/openstreetmap-forum/pull/2

**Pull request closed without merging**
