### PR TITLE
add Mod 'Easy BBCode'

### PR DESCRIPTION
**Pull request by Haikuch**
many users are asking for the bbcode buttons and the quick quote function that once has been active in the forum

### CODE REVIEW

**Comment by tomhughes** [comment]
Merged as e1d4d7db294492e2e53c33a86ec6628cf021a66d.

**Comment by Haikuch** [comment]
that broke somethin, https://forum.openstreetmap.org/viewtopic.php?id=56182 not working, do you get error logs?

**Comment by tomhughes** [comment]
Uncaught Error: Call to undefined function mysql_escape_string() in /srv/forum.openstreetmap.org/html/viewtopic.php:362

**Comment by tomhughes** [comment]
Suspect this should be `$db->escape()` to cope with different drivers? Likely we are using mysqli?

**Comment by tomhughes** [comment]
Have rolled back to previous version for now anyway.

**Comment by Haikuch** [comment]
dont understand where that error comes from, I cant find a mysql_escape_string() anywhere in the sourcecode, line 362 in viewtopic cant also be the reason: https://github.com/Haikuch/openstreetmap-forum/blob/1fc02fbb033ae9015042b5af82e8010ca79c2be8/viewtopic.php#L362

**Comment by tomhughes** [comment]
It's line 363 in that version.

**Comment by Haikuch** [comment]
ok, I will check that, what php and mysql versions are running on the server, so I can simulate the erros better locally?

**Comment by tomhughes** [comment]
It's PHP 7.0 and the mysql extension seems to be the same version so is presumably part of the PHP distribution itself.

**Comment by Haikuch** [comment]
yes its because of php 7, mysql functions have been removed there. I changed my local folder to php 7 now, so in the future I can test problems like that.

**Comment by tomhughes** [comment]
I think the `$db->escape` routine copes though because it tries `mysql_real_escape_string` first which I assume is the new name?

**Comment by Haikuch** [comment]
`$db->escape` is fine, I fixed it now and did a [new pull request.](https://github.com/openstreetmap/openstreetmap-forum/issues/6) I was checking everything again with the php7 version now. At some places of the software old mysql_functions are still mentioned, but looks like they are not used. I will check that again later. 
But within this modification everything should be clean now.

**Comment by tomhughes** [comment]
So that db->escape change is the only different in #6 compares to #4 ?

**Comment by Haikuch** [comment]
yes

**Pull request closed without merging**
