### PR TITLE
Added some styles for responsive design

### PR DESCRIPTION
**Pull request by natrius**
Easy deletable in case something happens. Some Forum users would be really happy.

### CODE REVIEW

**Comment by tomhughes** [comment]
Is there any reason why this needs to be in this repo though? Can the styles not be deployed separately if they're basically just plugins?

**Comment by tomhughes** [comment]
BTW are these original (written by you) or have you taken them from somewhere else?

**Comment by natrius** [comment]
Because they are new styles for the forum and they need to be there, so they can be chosen. Where should they be stored elsewhere? And these are official available styles from https://fluxbb.org/resources/styles/ not altered until now.
If there would be problems it would be easy to delete anyhow, one folder and one *.css :)

**Comment by tomhughes** [comment]
Right so rather than committing them here we can just get chef to deploy them directly from the upstream source.

**Comment by natrius** [comment]
How would be the correct way to propose something like this? I would maybe check on the language packs (https://github.com/OSM-Forum/openstreetmap-forum/issues/8) and on an favicon as well https://github.com/OSM-Forum/openstreetmap-forum/issues/10 -> for this is some alteration in the template needed as well. Or better not touch it at all as far as possible?

**Comment by tomhughes** [comment]
I'm already looking into it but sadly it's not completely trivial due to phpbb being a bit prehistoric.

**Comment by tomhughes** [comment]
By the way, how did you even download the `Midnight` one? The download links don't seem to work for me... Did you take it from the github repo?

**Comment by natrius** [comment]
It is "Midnight flat" actually. Sorry about the confusion. 
https://fluxbb.org/resources/styles/midnight-flat-responsive/ Midnight is from 2011 and midnight flat from 2016 and responsive.

**Comment by tomhughes** [comment]
Implemented in https://github.com/openstreetmap/chef/commit/3550857cf944749c93729637f8df40a7c45d709b.

**Comment by Nakaner** [comment]
Thank you, @tomhughes, for adding the styles. I myself would prefer to see the Victory theme being used as default because the default style is still not responsive if you are not logged in. The Victory theme is quite similar in terms of fonts and colours to the old default style.

**Comment by natrius** [comment]
Actually, no, please not. It does not look good right now, i will set up my own fluxBB and check some styles. I will try Air2 and i might change it if there is something needed. Midnight flat and Victory had some errors when i checked now.

I thought they will work instantly. :/

**Comment by kiezkickerde** [comment]
Well, https://forum.openstreetmap.org/style/Victory/img/logo.gif should be changed with something more osm-specific. ;-) (banner on top of the forum, desktop-mode)

**Comment by natrius** [comment]
Okay, i uploaded a new style to the official site. I changed the victory in some small things so it reflects the original Air more and some sidebar is not persent anymore. It looks not bad now on mobile and you can try it out on https://www.natrius.eu/fluxbb/ with your cellphone as well. The code as well is available at https://github.com/natrius/air3

https://fluxbb.org/resources/styles/air3/

If i get that correct, that would be the chef-code @tomhughes 

```
notifies :reload, "service[apache2]"
end

remote_file "/var/cache/chef/air3_v0.6.zip" do
  action :create_if_missing
  source "https://fluxbb.org/resources/styles/air3/releases/0.6/air3_v0.6.zip"
  owner "root"
  group "root"
  mode 0o644
  backup false
end

execute "/var/cache/chef/air3_v0.6.zip" do
  action :nothing
  command "unzip -qq /var/cache/chef/air3_v0.6.zip Air3.css Air3/*"
  cwd "/srv/forum.openstreetmap.org/html/style"
  user "forum"
  group "forum"
  subscribes :run, "remote_file[/var/cache/chef/air3_v0.6.zip]", :immediately
end

directory "/srv/forum.openstreetmap.org/html/cache/" do
  owner "www-data"
  group "www-data"
```

**Comment by tomhughes** [comment]
Did you intend that as an additional style? or to replace one of the others?

**Comment by natrius** [comment]
Replace both (Midnight and Victory) because they both do not work as intended. I set up my own FluxBB forum so i can test styles before suggesting more or making changes to mine so i can minimize the work for you. This one is now checked and should work so far as i could see.

**Comment by tomhughes** [comment]
That's all done now.

**Comment by natrius** [comment]
Amazing, thank you for you effort, i'm trying it already. 

So, one thing left: How can i proceed from now on if i have updates to the style? I would let the austrian community test it and give me feedback if there is anything to do. Just inform you through here or an e-mail somewhere?

**Comment by tomhughes** [comment]
Opening a PR on https://github.com/openstreetmap/chef/ to update the new version would be good...

**Pull request closed without merging**
